### ISSUE TITLE
Does not work with latest Truffle version 0.22

### ISSUE THREAD

**Issue by thomaswue** [graalvm/simplelanguage#17]
Needs to be updated according to https://twitter.com/larsschuetze/status/819891521071804417

**Comment by jtulach** [comment]
A bug report shall include steps to reproduce. Twitter's 140 character limit may not be the right medium for doing that. At least I am not able to understand what is the problem. Imho: close as *incomplete*.

**Comment by thomaswue** [comment]
Steps for reproduction:
1. Clone SL repository using git clone https://github.com/graalvm/simplelanguage
2. Download Graal VM Development Kit from http://www.oracle.com/technetwork/oracle-labs/program-languages/downloads
3. Unpack the downloaded graalvm_*.tar.gz into simplelanguage/graalvm.
4. Upgrade Truffle version in pom.xml to >= 0.16
5. Execute mvn package

**Comment by lschuetze** [comment]
With Truffle 0.17 the deprecated `com.oracle.truffle.api.instrument` package has been removed. Classes from within the package are still used in the code. I could work around by deleting [the following code](https://github.com/graalvm/simplelanguage/blob/a9dda7f3769d96cef4fd2d2f65db020476385fb4/src/test/java/com/oracle/truffle/sl/test/instrument/SLInstrumentTestRunner.java#L293-L310) which seems to add no harm. Tests will fail because `TruffleTck` improved and now has methods which throw `UnsupportedOperationException`.

**Comment by chumer** [comment]
I know what to do I will fix this now.

**Comment by chumer** [comment]
Fixed it. Sorry for the inconvenience.
